spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    url: jdbc:h2:tcp://localhost/~/concert #4칸
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: create #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        #show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸
  redis:
    host: localhost
    port: 6379


logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸
logging.level.org.hibernate.orm.jdbc.bind: trace
payment.topic-name: testTopic

